# Generated by Django 2.0.5 on 2018-06-01 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_post', models.TextField()),
                ('date_of_post', models.DateField()),
                ('title_of_post', models.CharField(max_length=200)),
            ],
        ),
    ]
