# Generated by Django 2.0.5 on 2018-08-13 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_of_post', models.CharField(max_length=200)),
                ('date_of_post', models.DateField()),
                ('blog_post', models.TextField()),
                ('slug', models.SlugField(blank=True, default='')),
            ],
        ),
    ]
