# Generated by Django 2.2.3 on 2019-07-07 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_vis', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DataVis',
        ),
    ]
