# Generated by Django 2.2.3 on 2019-07-08 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('data_vis', '0002_delete_datavis'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataVis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_of_post', models.CharField(max_length=200)),
                ('date_of_post', models.DateField()),
                ('slug', models.SlugField(blank=True, default='')),
                ('seo_description', models.CharField(max_length=200)),
                ('publish', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='DataVisFigure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('graph_title', models.CharField(max_length=200)),
                ('json_graph', models.TextField()),
                ('main_fig', models.BooleanField()),
                ('data_vis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_vis.DataVis')),
            ],
        ),
    ]
