# Generated by Django 2.2.3 on 2019-07-16 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_vis', '0003_datavis_datavisfigure'),
    ]

    operations = [
        migrations.AddField(
            model_name='datavisfigure',
            name='view_order',
            field=models.IntegerField(default=0),
        ),
    ]
