# Generated by Django 2.2.3 on 2019-07-17 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_vis', '0004_datavisfigure_view_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='datavis',
            name='intro_text',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='datavisfigure',
            name='fig_text',
            field=models.TextField(default=''),
        ),
    ]
