# Generated by Django 2.2.3 on 2019-07-17 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_vis', '0005_auto_20190717_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='datavis',
            name='homepage_chart_image',
            field=models.TextField(default=''),
        ),
    ]
