# Generated by Django 2.2.3 on 2019-07-19 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_vis', '0006_datavis_homepage_chart_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datavis',
            name='homepage_chart_image',
            field=models.ImageField(upload_to='static/images/'),
        ),
    ]
