# Generated by Django 2.2.3 on 2019-07-19 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_vis', '0007_auto_20190719_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datavis',
            name='homepage_chart_image',
            field=models.ImageField(upload_to='static/images/data_vis'),
        ),
    ]
