# Generated by Django 2.2.3 on 2019-08-17 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_vis', '0009_datavis_template_to_use'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datavisfigure',
            name='main_fig',
        ),
        migrations.RemoveField(
            model_name='datavisfigure',
            name='view_order',
        ),
        migrations.AlterField(
            model_name='datavis',
            name='template_to_use',
            field=models.CharField(choices=[['altair', 'Altair'], ['bokeh', 'Bokeh']], default='', max_length=10),
        ),
    ]
