# Generated by Django 3.0.10 on 2020-09-19 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_datavisindexpage_datavispage'),
    ]

    operations = [
        migrations.AddField(
            model_name='datavispage',
            name='bokeh_app',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
