# Generated by Django 2.0.5 on 2018-08-18 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20180818_1810'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SeoKeywords',
            new_name='SeoKeyword',
        ),
    ]
