# Generated by Django 2.2.3 on 2019-07-19 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20180818_1924'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='publish',
            field=models.BooleanField(default=False),
        ),
    ]
