# Generated by Django 2.2.3 on 2019-07-19 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_blogpost_publish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='publish',
            field=models.BooleanField(default=True),
        ),
    ]
